"""
CrawledPage Domain Model.

Represents a chunk of crawled documentation content with its embedding.
Maps to the archon_crawled_pages table.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class CrawledPageMetadata(BaseModel):
    """Metadata associated with a crawled page chunk."""

    chunk_size: int = Field(default=0, description="Size of the content chunk in characters")
    contextual_embedding: bool = Field(default=False, description="Whether contextual embedding was used")
    headers: str = Field(default="", description="Extracted headers from the chunk")
    source: str | None = Field(default=None, description="Source identifier for filtering")

    # Allow extra fields for flexibility
    model_config = {"extra": "allow"}


class CrawledPage(BaseModel):
    """
    A chunk of crawled documentation content.

    Represents a single chunk from a crawled page, including its content,
    metadata, and vector embedding for semantic search.

    Attributes:
        id: Unique identifier (UUID)
        url: Source URL of the page
        chunk_number: Order of this chunk within the page
        content: The text content of this chunk
        metadata: Additional metadata (source, headers, etc.)
        embedding_*: Vector embeddings for different dimensions
        source_id: Foreign key to archon_sources
        page_id: Foreign key to archon_pages (optional)
        created_at: When the chunk was created
    """

    id: str | None = Field(default=None, description="UUID primary key")
    url: str = Field(..., description="Source URL of the page")
    chunk_number: int = Field(default=0, description="Chunk order within the page")
    content: str = Field(..., description="Text content of this chunk")
    metadata: CrawledPageMetadata | dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata"
    )
    source_id: str = Field(..., description="Foreign key to archon_sources")
    page_id: str | None = Field(default=None, description="Foreign key to archon_pages")

    # Embedding columns - support multiple dimensions
    embedding_768: list[float] | None = Field(default=None, description="768-dim embedding")
    embedding_1024: list[float] | None = Field(default=None, description="1024-dim embedding")
    embedding_1536: list[float] | None = Field(default=None, description="1536-dim embedding (OpenAI)")
    embedding_3072: list[float] | None = Field(default=None, description="3072-dim embedding")

    # Model tracking
    llm_chat_model: str | None = Field(default=None, description="LLM model used for contextual embedding")
    embedding_model: str | None = Field(default=None, description="Embedding model used")
    embedding_dimension: int | None = Field(default=None, description="Dimension of the embedding")

    created_at: datetime | None = Field(default=None, description="Creation timestamp")

    def get_embedding(self) -> list[float] | None:
        """Get the active embedding based on embedding_dimension."""
        if self.embedding_dimension == 768:
            return self.embedding_768
        elif self.embedding_dimension == 1024:
            return self.embedding_1024
        elif self.embedding_dimension == 1536:
            return self.embedding_1536
        elif self.embedding_dimension == 3072:
            return self.embedding_3072
        # Fallback: return first non-None embedding
        return self.embedding_1536 or self.embedding_768 or self.embedding_1024 or self.embedding_3072


class CrawledPageCreate(BaseModel):
    """
    DTO for creating a new CrawledPage.

    Used when inserting new chunks into the repository.
    The id and created_at are auto-generated by the database.
    """

    url: str = Field(..., description="Source URL of the page")
    chunk_number: int = Field(default=0, description="Chunk order within the page")
    content: str = Field(..., description="Text content of this chunk")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    source_id: str = Field(..., description="Foreign key to archon_sources")
    page_id: str | None = Field(default=None, description="Foreign key to archon_pages")
    embedding: list[float] | None = Field(default=None, description="Vector embedding")
    embedding_dimension: int | None = Field(default=None, description="Embedding dimension")
    llm_chat_model: str | None = Field(default=None, description="LLM model used")
    embedding_model: str | None = Field(default=None, description="Embedding model used")
