#!/usr/bin/env python3
"""
Remediation script for AWS Access Key
Auto-generated by gitleaks-compliance extension
"""
import sys
import re
import argparse
from pathlib import Path

def remediate(file_path: str, line_number: int, pattern: str = r'AKIA[0-9A-Z]{16}', replacement: str = '<AWS_ACCESS_KEY_REMOVED>', dry_run: bool = False):
    """Remove AWS access key from file"""
    try:
        file_path = Path(file_path)
        if not file_path.exists():
            return {'success': False, 'message': f'File not found: {file_path}'}
        
        with open(file_path, 'r') as f:
            lines = f.readlines()
        
        if line_number < 1 or line_number > len(lines):
            return {'success': False, 'message': f'Invalid line number: {line_number}'}
        
        target_line = lines[line_number - 1]
        
        if re.search(pattern, target_line):
            new_line = re.sub(pattern, replacement, target_line)
            
            if dry_run:
                return {
                    'success': True,
                    'message': 'Dry run - no changes applied',
                    'changes': {
                        'file': str(file_path),
                        'line': line_number,
                        'old': target_line.strip(),
                        'new': new_line.strip()
                    }
                }
            
            lines[line_number - 1] = new_line
            
            with open(file_path, 'w') as f:
                f.writelines(lines)
            
            return {
                'success': True,
                'message': 'AWS access key removed',
                'changes': {
                    'file': str(file_path),
                    'line': line_number,
                    'old': target_line.strip(),
                    'new': new_line.strip()
                }
            }
        else:
            return {'success': False, 'message': 'AWS access key pattern not found'}
    
    except Exception as e:
        return {'success': False, 'message': f'Error: {str(e)}'}

def main():
    parser = argparse.ArgumentParser(description='Remediate AWS Access Key')
    parser.add_argument('--file', required=True, help='File path')
    parser.add_argument('--line', type=int, required=True, help='Line number')
    parser.add_argument('--pattern', default=r'AKIA[0-9A-Z]{16}', help='Pattern to match')
    parser.add_argument('--replacement', default='<AWS_ACCESS_KEY_REMOVED>', help='Replacement text')
    parser.add_argument('--dry-run', action='store_true', help='Show changes without applying')
    
    args = parser.parse_args()
    result = remediate(args.file, args.line, args.pattern, args.replacement, args.dry_run)
    
    print(f"Status: {'SUCCESS' if result['success'] else 'FAILED'}")
    print(f"Message: {result['message']}")
    if 'changes' in result:
        print(f"\nChanges:")
        print(f"  File: {result['changes']['file']}")
        print(f"  Line: {result['changes']['line']}")
        print(f"  Old:  {result['changes']['old']}")
        print(f"  New:  {result['changes']['new']}")
    
    sys.exit(0 if result['success'] else 1)

if __name__ == "__main__":
    main()
