import { access, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export async function generateRuntimeChecker(root: string, check: boolean): Promise<void> {
  const entry = join(root, '.archon/workflows/sdlc/verify-runtime/src/check-evidence.ts');
  try {
    await access(join(root, '.archon/workflows/sdlc/verify-runtime'));
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return;
    throw error;
  }
  const result = await Bun.build({
    entrypoints: [entry],
    target: 'bun',
    format: 'esm',
    minify: true,
  });
  if (!result.success || result.outputs.length !== 1)
    throw new Error(
      `runtime checker build failed: ${result.logs.map(log => log.message).join('\n')}`
    );
  const content = `// Generated by scripts/generate-runtime-checker.ts through generate:bundled.\n${await result.outputs[0].text()}`;
  const path = join(root, '.archon/workflows/sdlc/verify-runtime/scripts/check-evidence.js');
  if (check) {
    if ((await readFile(path, 'utf8')).replaceAll('\r\n', '\n') !== content)
      throw new Error('runtime checker is stale; run bun run generate:bundled');
  } else await writeFile(path, content);
}
