import { access, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export async function generateEvidenceScripts(root: string, check: boolean): Promise<void> {
  for (const [owner, name] of [
    ['verify-runtime', 'check-evidence'],
    ['merge-queue', 'merge-queue'],
    ['merge-queue', 'qualification'],
    ['lifecycle', 'qualification'],
  ]) {
    const packageDir = join(root, '.archon/workflows/sdlc', owner);
    const entry = join(packageDir, 'src', `${name}.ts`);
    try {
      await access(packageDir);
    } catch (error) {
      if (error instanceof Error && 'code' in error && error.code === 'ENOENT') continue;
      throw error;
    }
    const result = await Bun.build({
      entrypoints: [entry],
      target: 'bun',
      format: 'esm',
      minify: true,
    });
    if (!result.success || result.outputs.length !== 1)
      throw new Error(
        `${owner}/${name} build failed: ${result.logs.map(log => log.message).join('\n')}`
      );
    const content = `// Generated by scripts/generate-evidence-scripts.ts through generate:bundled.\n${await result.outputs[0].text()}`;
    const path = join(packageDir, 'scripts', `${name}.js`);
    if (check) {
      if ((await readFile(path, 'utf8')).replaceAll('\r\n', '\n') !== content)
        throw new Error(`${owner}/${name} is stale; run bun run generate:bundled`);
    } else await writeFile(path, content);
  }
}
