#!/usr/bin/env bun
/**
 * Append the extrapolated ACs from groomed-bug.json to the Jira ticket's
 * description. The append is idempotent: if a previous "Acceptance
 * Criteria (Archon-extrapolated)" section already exists in the
 * description, it's replaced rather than duplicated.
 *
 * task-implement's fetch-task-context downstream reads the description
 * to populate task-context.md; the dev agent and reviewer cascade need
 * the ACs to know what "fixed" looks like. Without this step, the bug
 * description usually says "X is broken" with no mention of what
 * correct behavior is.
 *
 * Reads:
 *   $ARTIFACTS_DIR/trigger-payload.json — issue_key
 *   $ARTIFACTS_DIR/groomed-bug.json     — extrapolated ACs
 *
 * Env:
 *   JIRA_BASE_URL, JIRA_USER_EMAIL, JIRA_API_TOKEN
 */
import { readFileSync } from 'node:fs';

const ARTIFACTS_DIR = process.env.ARTIFACTS_DIR;
if (!ARTIFACTS_DIR) {
  console.error('ARTIFACTS_DIR not set');
  process.exit(1);
}

const trigger = JSON.parse(
  readFileSync(`${ARTIFACTS_DIR}/trigger-payload.json`, 'utf8'),
);
const issueKey: string = trigger.issue_key;
if (!issueKey) {
  console.error('issue_key missing from trigger-payload.json');
  process.exit(1);
}

const groomed = JSON.parse(
  readFileSync(`${ARTIFACTS_DIR}/groomed-bug.json`, 'utf8'),
);
const acs: string[] = Array.isArray(groomed.acceptance_criteria)
  ? groomed.acceptance_criteria
  : [];

if (acs.length === 0) {
  console.log('No ACs to append; skipping.');
  process.stdout.write(JSON.stringify({ skipped: true, reason: 'no_acs' }));
  process.exit(0);
}

const baseUrl = process.env.JIRA_BASE_URL!;
const email = process.env.JIRA_USER_EMAIL!;
const token = process.env.JIRA_API_TOKEN!;
const auth = Buffer.from(`${email}:${token}`).toString('base64');

// Fetch the current description in plain text. Jira Cloud's API returns
// description in ADF; we ask for the rendered/wiki form which is easier
// to round-trip.
const getRes = await fetch(
  `${baseUrl}/rest/api/3/issue/${issueKey}?fields=description&expand=renderedFields`,
  {
    headers: {
      Authorization: `Basic ${auth}`,
      Accept: 'application/json',
    },
  },
);
if (!getRes.ok) {
  console.error(`Failed to fetch issue: HTTP ${getRes.status}`);
  process.exit(1);
}
const current = await getRes.json();

// Walk the current ADF description, flatten to plain text. Then append
// our ACs section. We rebuild the description as a fresh ADF doc with
// two paragraphs: the original text + our AC section. This loses
// formatting in the original description, but the test-strategy
// workflow only reads it as plain text via jira-fetch-task-context, so
// the round-trip is acceptable.

interface AdfNode {
  type: string;
  text?: string;
  content?: AdfNode[];
}

function flattenAdf(node: AdfNode | null | undefined): string {
  if (!node) return '';
  if (node.type === 'text' && typeof node.text === 'string') return node.text;
  if (Array.isArray(node.content)) {
    const sep =
      node.type === 'paragraph' || node.type === 'listItem' ? '\n' : '';
    return node.content.map(flattenAdf).join(sep);
  }
  return '';
}

const originalDescription = flattenAdf(current.fields?.description) || '';

// Strip a previously-appended Archon AC section so re-runs don't duplicate.
const SECTION_HEADER = 'Acceptance Criteria (Archon-extrapolated)';
const SECTION_RE = new RegExp(
  `\\n*## ${SECTION_HEADER}[\\s\\S]*$`,
  'm',
);
const cleanedOriginal = originalDescription.replace(SECTION_RE, '').trimEnd();

const acSection = [
  '',
  '',
  `## ${SECTION_HEADER}`,
  '',
  '_Generated by the bug-groom workflow. Edit if these don\'t match your intent._',
  '',
  ...acs.map((ac) => `- ${ac}`),
].join('\n');

const newDescription = cleanedOriginal + acSection;

// PUT the new description back as ADF (single paragraph node).
const putRes = await fetch(`${baseUrl}/rest/api/3/issue/${issueKey}`, {
  method: 'PUT',
  headers: {
    Authorization: `Basic ${auth}`,
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    fields: {
      description: {
        type: 'doc',
        version: 1,
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: newDescription }],
          },
        ],
      },
    },
  }),
});

if (!putRes.ok) {
  const t = await putRes.text();
  console.error(`Failed to update description: HTTP ${putRes.status}: ${t}`);
  process.exit(1);
}

console.log(`Appended ${acs.length} ACs to ${issueKey} description.`);
process.stdout.write(
  JSON.stringify({ appended: acs.length, issue_key: issueKey }),
);
